### PR TITLE
Add python extension

### PR DESCRIPTION
**Pull request by mathieu1**
The goal of this PR is to be able to `import pdal` in a lambda function (`python 3.7`).

This is work in progress. Steps required for completion include:
- [x] make `python -c "import pdal"` work in the Docker container
- [x] include the necessary python packages (pdal/python, numpy, cython, ...) in the lambda layer

 Currently I'm stuck at the first step with a segfault. The image seems to build fine. Then starting a shell in the container using `docker run --rm -it pdal-lambda:latest sh` I get:
```shell
sh-4.2# pdal --version
-------------------------------------------------------------------------
pdal 1.9.1 (git-version: 49eef8)
-------------------------------------------------------------------------

sh-4.2# python -c "import pdal"
Segmentation fault
```

Any pointers on how to move forward from here / debug would be greatly appreciated. Feel free to close in case the functionality is not desired in this repo.

### CODE REVIEW

**Comment by hobu** [comment]
The only python that would work is the same python version that the lambda layer was built against. This is due to how PDAL links and embeds Python. See https://github.com/PDAL/PDAL/issues/1981 and https://github.com/PDAL/PDAL/issues/1478 for background.

**Comment by mathieu1** [comment]
Thanks for the pointers. As far as I can tell, everything seems to be built against the correct python (the only python 3.7 in the container).
```shell
sh-4.2# which python
/var/lang/bin/python
sh-4.2# ldd /var/lang/lib/python3.7/site-packages/PDAL-2.1.8-py3.7-linux-x86_64.egg/pdal/libpdalpython.cpython-37m-x86_64-linux-gnu.so  | grep python
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fbc8e5cc000)
sh-4.2# ldd /usr/lib/libpdal_* | egrep '(\:|python)'
/usr/lib/libpdal_base.so:
/usr/lib/libpdal_base.so.8:
/usr/lib/libpdal_base.so.9.0.1:
/usr/lib/libpdal_plugin_filter_python.so:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fd99440a000)
/usr/lib/libpdal_plugin_filter_python.so.8:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fa338198000)
/usr/lib/libpdal_plugin_filter_python.so.9.0.1:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fe641234000)
/usr/lib/libpdal_plugin_kernel_fauxplugin.so:
/usr/lib/libpdal_plugin_kernel_fauxplugin.so.8:
/usr/lib/libpdal_plugin_kernel_fauxplugin.so.9.0.1:
/usr/lib/libpdal_plugin_reader_i3s.so:
/usr/lib/libpdal_plugin_reader_i3s.so.8:
/usr/lib/libpdal_plugin_reader_i3s.so.9.0.1:
/usr/lib/libpdal_plugin_reader_numpy.so:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fa438bde000)
/usr/lib/libpdal_plugin_reader_numpy.so.8:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007fe6e2fca000)
/usr/lib/libpdal_plugin_reader_numpy.so.9.0.1:
	libpython3.7m.so.1.0 => /var/lang/lib/libpython3.7m.so.1.0 (0x00007f140bfd4000)
/usr/lib/libpdal_plugin_reader_slpk.so:
/usr/lib/libpdal_plugin_reader_slpk.so.8:
/usr/lib/libpdal_plugin_reader_slpk.so.9.0.1:
/usr/lib/libpdal_util.so:
/usr/lib/libpdal_util.so.8:
/usr/lib/libpdal_util.so.9.0.1:
sh-4.2# python -c "import pdal"
Segmentation fault
```

Moreover neither the numpy reader nor the python filter work:

```shell
sh-4.2# pdal info /var/task/PDAL/test/data/plang/perlin.npy --readers.numpy.dimension=Intensity --readers.numpy.assign_z=4
Segmentation fault
```

```shell
sh-4.2# cat multiply_z.py
import numpy as np

def multiply_z(ins,outs):
    Z = ins['Z']
    Z = Z * 10.0
    outs['Z'] = Z
    return True

sh-4.2# cat pipeline.json
[
    "/var/task/PDAL/test/data/autzen/autzen.las",
    {
        "type":"filters.python",
        "script":"multiply_z.py",
        "function":"multiply_z",
        "module":"anything"
    },
    {
        "type":"writers.las",
        "filename":"file-output.las"
    }
]
sh-4.2# pdal pipeline -i pipeline.json
Segmentation fault
```

**Comment by hobu** [comment]
Can you try applying this patch to the PDAL build? https://github.com/PDAL/PDAL/commit/e3d83eba24de60795c4b005c6d183ba6738ebab9

**Comment by mathieu1** [comment]
Doesn't seem to help (I tried both that extact commit, and only the specific patch rebased on top of 1.9.1).

For now I might resort to a workaround combining a `pdal` pipeline writing to a temporary output file, and loading the data in python using `laspy`.

Happy to try out other suggestions.

**Comment by hobu** [comment]
Does this replicate in the Docker container, and can you possibly get a traceback from gdb?

**Comment by mathieu1** [comment]
Thanks for the `gdb` suggestion, I got this out of it:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffef34c3b2 in loadPython() () from /usr/lib/libpdal_plugin_reader_numpy.so.8
```
The issue was that `PDAL_PYTHON_LIBRARY` was not set. Once it is set to `libpython3.so`, everything works correctly :tada:. (Actually, the `HOME` variable needs to be set in order to avoid trouble).

It's unclear to me if environment variables can be set at the lambda layer level, so the way I end up using pdal is by doing:
```python
import os
os.environ['PDAL_PYTHON_LIBRARY'] = 'libpython3.so'
os.environ['HOME'] = '/var/task'
import pdal
```

I also tried to use the option `-DPDAL_PYTHON_LIBRARY="libpython3.so"` like is done in the [conda recipe for pdal](https://github.com/conda-forge/pdal-feedstock/blob/63145ea449376a185525eee4a83a96f4fe12a35c/recipe/build.sh#L19), but that seems to be ignored when building pdal.

Do you aim at merging this PR, given the need for this environment variable hack? If so, I can give a crack at documenting the hack in the README.

**Comment by hobu** [comment]
PDAL has been having issues with `PDAL_PYTHON_LIBRARY` in other contexts. We should fix the issue there, but I'm happy to merge this PR as-is for now and re-push the layers. Thanks for the contribution!

**Comment by hobu** [comment]
See https://github.com/PDAL/PDAL/pull/2598

**Comment by mathieu1** [comment]
I confirm that using PDAL master (including the yet-to-be-merged PDAL/PDAL#2601 ) solves the `PDAL_PYTHON_LIBRARY` issue, so this is ready to merge for me.

**Pull request closed without merging**
